services:
  - type: web
    name: your-bot-name
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENWEATHER_API_KEYS
        sync: false
      - key: NEWS_API
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://telegrambot-9s8l.onrender.com/